name: gitea

networks:
  ingress-traefik:
    external: true
  default: {}

services:
  gitea:
    image: ${GITEA_APP_IMAGE}
    container_name: ${GITEA_APP_CONTAINER}
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - ingress-traefik
      - default
    ports:
      - ${GITEA_APP_SSH_PORT}:22/tcp
    environment:
      - TZ=${TIMEZONE}
      # User
      - USER_UID=1000
      - USER_GID=1000
      # Server
      - GITEA__server__ROOT_URL=https://${GITEA_APP_DOMAIN}
      - GITEA__server__LFS_START_SERVER=true
      # Database
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${GITEA_POSTGRES_CONTAINER}:5432
      - GITEA__database__USER=${GITEA_POSTGRES_USER}
      - GITEA__database__PASSWD=${GITEA_POSTGRES_PASSWORD}
      - GITEA__database__NAME=${GITEA_POSTGRES_DB}
      # Indexer
      - GITEA__indexer__ISSUE_INDEXER_TYPE=bleve
      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__indexer__REPO_INDEXER_TYPE=bleve
      # Session
      - GITEA__session__PROVIDER=db
      # Mailer
      - GITEA__mailer__ENABLED=${GITEA_APP_MAILER_ENABLED}
      - GITEA__mailer__PROTOCOL=${GITEA_APP_MAILER_PROTOCOL}
      - GITEA__mailer__SMTP_ADDR=${GITEA_APP_MAILER_SMTP_ADDR}
      - GITEA__mailer__SMTP_PORT=${GITEA_APP_MAILER_SMTP_PORT}
      - GITEA__mailer__USER=${GITEA_APP_MAILER_USER}
      - GITEA__mailer__PASSWD=${GITEA_APP_MAILER_PASSWD}
      - GITEA__mailer__FROM=${GITEA_APP_MAILER_FROM}
    volumes:
      - ${ROOT_DIR}/data:/data
    healthcheck:
      test: curl -fSs localhost:3000/api/healthz || exit 1
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 30s
    labels:
      - traefik.enable=true
      # routers
      - traefik.http.routers.gitea-app.rule=Host(`${GITEA_APP_DOMAIN}`)
      - traefik.http.routers.gitea-app.entrypoints=web,websecure
      - traefik.http.routers.gitea-app.service=gitea-app@docker
      # services
      - traefik.http.services.gitea-app.loadbalancer.server.port=3000

  postgres:
    image: ${GITEA_POSTGRES_IMAGE}
    container_name: ${GITEA_POSTGRES_CONTAINER}
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_USER=${GITEA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${GITEA_POSTGRES_PASSWORD}
      - POSTGRES_DB=${GITEA_POSTGRES_DB}
    volumes:
      - ${ROOT_DIR}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
